
/*
 * Database Schema Export
 * Generated by: SQL Extract v1.0.0
 * Date: 2025-10-18 16:41:01
 */

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- TABLES

CREATE TABLE [dbo].[Users] (
    [UserId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [Email] nvarchar(256) NOT NULL,
    [FirstName] nvarchar(100) NOT NULL,
    [LastName] nvarchar(100) NOT NULL,
    [AzureAdB2CObjectId] nvarchar(128) NULL,
    [IsActive] bit NOT NULL DEFAULT ((1)),
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [ModifiedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [PasswordHash] nvarchar(500) NULL,
    [PasswordSalt] nvarchar(500) NULL,
    [RefreshToken] nvarchar(500) NULL,
    [RefreshTokenExpiryDate] datetime2(7) NULL,
    [LastLoginDate] datetime2(7) NULL,
    [EmailConfirmed] bit NOT NULL DEFAULT ((0)),
    [PhoneNumber] nvarchar(20) NULL,
    [MfaEnabled] bit NOT NULL DEFAULT ((0))
)
GO
CREATE TABLE [dbo].[ChecklistTemplates] (
    [TemplateId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [TenantId] uniqueidentifier NULL,
    [TemplateName] nvarchar(200) NOT NULL,
    [InspectionType] nvarchar(50) NOT NULL,
    [Standard] nvarchar(50) NOT NULL,
    [IsSystemTemplate] bit NOT NULL DEFAULT ((0)),
    [IsActive] bit NOT NULL DEFAULT ((1)),
    [Description] nvarchar(1000) NULL,
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [ModifiedDate] datetime2(7) NULL
)
GO
CREATE TABLE [dbo].[Tenants] (
    [TenantId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [TenantCode] nvarchar(50) NOT NULL,
    [CompanyName] nvarchar(200) NOT NULL,
    [SubscriptionTier] nvarchar(50) NOT NULL,
    [IsActive] bit NOT NULL DEFAULT ((1)),
    [MaxLocations] int NOT NULL DEFAULT ((10)),
    [MaxUsers] int NOT NULL DEFAULT ((5)),
    [MaxExtinguishers] int NOT NULL DEFAULT ((100)),
    [DatabaseSchema] nvarchar(128) NOT NULL,
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [ModifiedDate] datetime2(7) NOT NULL DEFAULT (getutcdate())
)
GO
CREATE TABLE [dbo].[AuditLog] (
    [AuditLogId] bigint IDENTITY(1,1) NOT NULL,
    [TenantId] uniqueidentifier NOT NULL,
    [UserId] uniqueidentifier NULL,
    [Action] nvarchar(100) NOT NULL,
    [EntityType] nvarchar(100) NULL,
    [EntityId] nvarchar(128) NULL,
    [OldValues] nvarchar NULL,
    [NewValues] nvarchar NULL,
    [IpAddress] nvarchar(45) NULL,
    [UserAgent] nvarchar(500) NULL,
    [Timestamp] datetime2(7) NOT NULL DEFAULT (getutcdate())
)
GO
CREATE TABLE [dbo].[SystemRoles] (
    [SystemRoleId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [RoleName] nvarchar(50) NOT NULL,
    [Description] nvarchar(500) NULL,
    [IsActive] bit NOT NULL DEFAULT ((1)),
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate())
)
GO
CREATE TABLE [dbo].[ExtinguisherTypes] (
    [ExtinguisherTypeId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [TypeCode] nvarchar(50) NOT NULL,
    [TypeName] nvarchar(200) NOT NULL,
    [Description] nvarchar NULL,
    [MonthlyInspectionRequired] bit NOT NULL DEFAULT ((1)),
    [AnnualInspectionRequired] bit NOT NULL DEFAULT ((1)),
    [HydrostaticTestYears] int NULL,
    [IsActive] bit NOT NULL DEFAULT ((1)),
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [TenantId] uniqueidentifier NOT NULL DEFAULT ('00000000-0000-0000-0000-000000000000')
)
GO
CREATE TABLE [dbo].[ChecklistItems] (
    [ChecklistItemId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [TemplateId] uniqueidentifier NOT NULL,
    [ItemText] nvarchar(500) NOT NULL,
    [ItemDescription] nvarchar(1000) NULL,
    [Order] int NOT NULL,
    [Category] nvarchar(50) NOT NULL,
    [Required] bit NOT NULL DEFAULT ((1)),
    [RequiresPhoto] bit NOT NULL DEFAULT ((0)),
    [RequiresComment] bit NOT NULL DEFAULT ((0)),
    [PassFailNA] bit NOT NULL DEFAULT ((1)),
    [VisualAid] nvarchar(500) NULL,
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [TenantId] uniqueidentifier NOT NULL DEFAULT ('00000000-0000-0000-0000-000000000000')
)
GO
CREATE TABLE [dbo].[Locations] (
    [LocationId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [TenantId] uniqueidentifier NOT NULL,
    [LocationCode] nvarchar(50) NOT NULL,
    [LocationName] nvarchar(200) NOT NULL,
    [AddressLine1] nvarchar(200) NULL,
    [AddressLine2] nvarchar(200) NULL,
    [City] nvarchar(100) NULL,
    [StateProvince] nvarchar(100) NULL,
    [PostalCode] nvarchar(20) NULL,
    [Country] nvarchar(100) NULL,
    [ContactName] nvarchar(200) NULL,
    [ContactPhone] nvarchar(50) NULL,
    [ContactEmail] nvarchar(200) NULL,
    [IsActive] bit NOT NULL DEFAULT ((1)),
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [ModifiedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [Latitude] decimal(10,7) NULL,
    [Longitude] decimal(10,7) NULL,
    [LocationBarcodeData] nvarchar(500) NULL
)
GO
CREATE TABLE [dbo].[InspectionTypes] (
    [InspectionTypeId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [TenantId] uniqueidentifier NOT NULL,
    [TypeName] nvarchar(200) NOT NULL,
    [Description] nvarchar NULL,
    [RequiresServiceTechnician] bit NOT NULL DEFAULT ((0)),
    [FrequencyDays] int NOT NULL DEFAULT ((365)),
    [IsActive] bit NOT NULL DEFAULT ((1)),
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate())
)
GO
CREATE TABLE [dbo].[UserTenantRoles] (
    [UserTenantRoleId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [UserId] uniqueidentifier NOT NULL,
    [TenantId] uniqueidentifier NOT NULL,
    [RoleName] nvarchar(50) NOT NULL,
    [IsActive] bit NOT NULL DEFAULT ((1)),
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate())
)
GO
CREATE TABLE [dbo].[UserSystemRoles] (
    [UserSystemRoleId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [UserId] uniqueidentifier NOT NULL,
    [SystemRoleId] uniqueidentifier NOT NULL,
    [IsActive] bit NOT NULL DEFAULT ((1)),
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate())
)
GO
CREATE TABLE [dbo].[Extinguishers] (
    [ExtinguisherId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [TenantId] uniqueidentifier NOT NULL,
    [LocationId] uniqueidentifier NOT NULL,
    [ExtinguisherTypeId] uniqueidentifier NOT NULL,
    [AssetTag] nvarchar(100) NOT NULL,
    [BarcodeData] nvarchar(500) NULL,
    [Manufacturer] nvarchar(200) NULL,
    [Model] nvarchar(200) NULL,
    [SerialNumber] nvarchar(200) NULL,
    [ManufactureDate] date NULL,
    [InstallDate] date NULL,
    [LastHydrostaticTestDate] date NULL,
    [Capacity] nvarchar(50) NULL,
    [LocationDescription] nvarchar(500) NULL,
    [IsActive] bit NOT NULL DEFAULT ((1)),
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [ModifiedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [IsOutOfService] bit NOT NULL DEFAULT ((0)),
    [OutOfServiceReason] nvarchar(500) NULL
)
GO
CREATE TABLE [dbo].[InspectionChecklistTemplates] (
    [ChecklistTemplateId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [TenantId] uniqueidentifier NOT NULL,
    [InspectionTypeId] uniqueidentifier NOT NULL,
    [TemplateName] nvarchar(200) NOT NULL,
    [IsActive] bit NOT NULL DEFAULT ((1)),
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate())
)
GO
CREATE TABLE [dbo].[MaintenanceRecords] (
    [MaintenanceRecordId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [ExtinguisherId] uniqueidentifier NOT NULL,
    [MaintenanceType] nvarchar(100) NOT NULL,
    [MaintenanceDate] date NOT NULL,
    [TechnicianName] nvarchar(200) NULL,
    [ServiceCompany] nvarchar(200) NULL,
    [Cost] decimal(10,2) NULL,
    [Notes] nvarchar NULL,
    [ReceiptBlobPath] nvarchar(500) NULL,
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [TenantId] uniqueidentifier NOT NULL DEFAULT ('00000000-0000-0000-0000-000000000000')
)
GO
CREATE TABLE [dbo].[Inspections] (
    [InspectionId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [TenantId] uniqueidentifier NOT NULL,
    [ExtinguisherId] uniqueidentifier NOT NULL,
    [InspectionTypeId] uniqueidentifier NOT NULL,
    [InspectorUserId] uniqueidentifier NOT NULL,
    [InspectionDate] datetime2(7) NOT NULL,
    [Passed] bit NOT NULL DEFAULT ((0)),
    [IsAccessible] bit NOT NULL DEFAULT ((1)),
    [HasObstructions] bit NOT NULL DEFAULT ((0)),
    [SignageVisible] bit NOT NULL DEFAULT ((1)),
    [SealIntact] bit NOT NULL DEFAULT ((0)),
    [PinInPlace] bit NOT NULL DEFAULT ((0)),
    [NozzleClear] bit NOT NULL DEFAULT ((0)),
    [HoseConditionGood] bit NOT NULL DEFAULT ((0)),
    [GaugeInGreenZone] bit NOT NULL DEFAULT ((0)),
    [GaugePressurePsi] decimal(6,2) NULL,
    [PhysicalDamagePresent] bit NOT NULL DEFAULT ((0)),
    [InspectionTagAttached] bit NOT NULL DEFAULT ((1)),
    [RequiresService] bit NOT NULL DEFAULT ((0)),
    [RequiresReplacement] bit NOT NULL DEFAULT ((0)),
    [Notes] nvarchar NULL,
    [FailureReason] nvarchar NULL,
    [CorrectiveAction] nvarchar NULL,
    [GpsLatitude] decimal(10,7) NULL,
    [GpsLongitude] decimal(10,7) NULL,
    [DeviceId] nvarchar(200) NULL,
    [TamperProofHash] nvarchar(100) NULL,
    [PreviousInspectionHash] nvarchar(100) NULL,
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [InspectionType] nvarchar(50) NULL,
    [GpsAccuracyMeters] int NULL,
    [LocationVerified] bit NOT NULL DEFAULT ((0)),
    [DamageDescription] nvarchar NULL,
    [WeightPounds] decimal(10,2) NULL,
    [WeightWithinSpec] bit NOT NULL DEFAULT ((1)),
    [PreviousInspectionDate] nvarchar(50) NULL,
    [PhotoUrls] nvarchar NULL,
    [DataHash] nvarchar(512) NULL,
    [InspectorSignature] nvarchar(512) NULL,
    [SignedDate] datetime2(7) NULL,
    [IsVerified] bit NOT NULL DEFAULT ((0)),
    [ModifiedDate] datetime2(7) NULL DEFAULT (getutcdate())
)
GO
CREATE TABLE [dbo].[InspectionChecklistResponses] (
    [ResponseId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [InspectionId] uniqueidentifier NOT NULL,
    [ChecklistItemId] uniqueidentifier NOT NULL,
    [Response] nvarchar(10) NOT NULL,
    [Comment] nvarchar(1000) NULL,
    [PhotoId] uniqueidentifier NULL,
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [TenantId] uniqueidentifier NOT NULL DEFAULT ('00000000-0000-0000-0000-000000000000')
)
GO
CREATE TABLE [dbo].[InspectionPhotos] (
    [PhotoId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [InspectionId] uniqueidentifier NOT NULL,
    [PhotoType] nvarchar(50) NOT NULL,
    [BlobUrl] nvarchar(500) NOT NULL,
    [ThumbnailUrl] nvarchar(500) NULL,
    [FileSize] bigint NULL,
    [MimeType] nvarchar(100) NULL,
    [CaptureDate] datetime2(7) NULL,
    [Latitude] decimal(9,6) NULL,
    [Longitude] decimal(9,6) NULL,
    [DeviceModel] nvarchar(200) NULL,
    [EXIFData] nvarchar NULL,
    [Notes] nvarchar(500) NULL,
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [TenantId] uniqueidentifier NOT NULL DEFAULT ('00000000-0000-0000-0000-000000000000')
)
GO
CREATE TABLE [dbo].[InspectionDeficiencies] (
    [DeficiencyId] uniqueidentifier NOT NULL DEFAULT (newid()),
    [InspectionId] uniqueidentifier NOT NULL,
    [DeficiencyType] nvarchar(50) NOT NULL,
    [Severity] nvarchar(20) NOT NULL,
    [Description] nvarchar(1000) NOT NULL,
    [Status] nvarchar(20) NOT NULL DEFAULT ('Open'),
    [ActionRequired] nvarchar(500) NULL,
    [EstimatedCost] decimal(10,2) NULL,
    [AssignedToUserId] uniqueidentifier NULL,
    [DueDate] date NULL,
    [ResolutionNotes] nvarchar(1000) NULL,
    [ResolvedDate] datetime2(7) NULL,
    [ResolvedByUserId] uniqueidentifier NULL,
    [PhotoIds] nvarchar NULL,
    [CreatedDate] datetime2(7) NOT NULL DEFAULT (getutcdate()),
    [ModifiedDate] datetime2(7) NULL,
    [TenantId] uniqueidentifier NOT NULL DEFAULT ('00000000-0000-0000-0000-000000000000')
)
GO
