
/*
 * Database Schema Export
 * Generated by: SQL Extract v1.0.0
 * Date: 2025-10-18 16:41:01
 */

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- PRIMARY KEYS


ALTER TABLE [dbo].[AuditLog]
ADD CONSTRAINT [PK_AuditLog] PRIMARY KEY CLUSTERED ([AuditLogId])
GO


ALTER TABLE [dbo].[ChecklistItems]
ADD CONSTRAINT [PK__Checklis__407798EDAED243DF] PRIMARY KEY CLUSTERED ([ChecklistItemId])
GO


ALTER TABLE [dbo].[ChecklistTemplates]
ADD CONSTRAINT [PK__Checklis__F87ADD27282D4F82] PRIMARY KEY CLUSTERED ([TemplateId])
GO


ALTER TABLE [dbo].[Extinguishers]
ADD CONSTRAINT [PK__Extingui__DEF699973EA75343] PRIMARY KEY CLUSTERED ([ExtinguisherId])
GO


ALTER TABLE [dbo].[ExtinguisherTypes]
ADD CONSTRAINT [PK__Extingui__F98EFD4404D39164] PRIMARY KEY CLUSTERED ([ExtinguisherTypeId])
GO


ALTER TABLE [dbo].[InspectionChecklistResponses]
ADD CONSTRAINT [PK__Inspecti__1AAA646CF73A9CBD] PRIMARY KEY CLUSTERED ([ResponseId])
GO


ALTER TABLE [dbo].[InspectionChecklistTemplates]
ADD CONSTRAINT [PK_tenant_60C74CCA6CD0490193D472F3EFFF38B5_ChecklistTemplates] PRIMARY KEY CLUSTERED ([ChecklistTemplateId])
GO


ALTER TABLE [dbo].[InspectionDeficiencies]
ADD CONSTRAINT [PK__Inspecti__43B63A62B27B356C] PRIMARY KEY CLUSTERED ([DeficiencyId])
GO


ALTER TABLE [dbo].[InspectionPhotos]
ADD CONSTRAINT [PK__Inspecti__21B7B5E2862BA5DA] PRIMARY KEY CLUSTERED ([PhotoId])
GO


ALTER TABLE [dbo].[Inspections]
ADD CONSTRAINT [PK__Inspecti__30B2DC08E03586DC] PRIMARY KEY CLUSTERED ([InspectionId])
GO


ALTER TABLE [dbo].[InspectionTypes]
ADD CONSTRAINT [PK__Inspecti__151652578232D1A3] PRIMARY KEY CLUSTERED ([InspectionTypeId])
GO


ALTER TABLE [dbo].[Locations]
ADD CONSTRAINT [PK__Location__E7FEA4973D6E5E2E] PRIMARY KEY CLUSTERED ([LocationId])
GO


ALTER TABLE [dbo].[MaintenanceRecords]
ADD CONSTRAINT [PK_tenant_60C74CCA6CD0490193D472F3EFFF38B5_Maintenance] PRIMARY KEY CLUSTERED ([MaintenanceRecordId])
GO


ALTER TABLE [dbo].[SystemRoles]
ADD CONSTRAINT [PK_SystemRoles] PRIMARY KEY CLUSTERED ([SystemRoleId])
GO


ALTER TABLE [dbo].[Tenants]
ADD CONSTRAINT [PK_Tenants] PRIMARY KEY CLUSTERED ([TenantId])
GO


ALTER TABLE [dbo].[Users]
ADD CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([UserId])
GO


ALTER TABLE [dbo].[UserSystemRoles]
ADD CONSTRAINT [PK_UserSystemRoles] PRIMARY KEY CLUSTERED ([UserSystemRoleId])
GO


ALTER TABLE [dbo].[UserTenantRoles]
ADD CONSTRAINT [PK_UserTenantRoles] PRIMARY KEY CLUSTERED ([UserTenantRoleId])
GO

-- UNIQUE CONSTRAINTS


ALTER TABLE [dbo].[Extinguishers]
ADD CONSTRAINT [UQ_Extinguishers_TenantAssetTag] UNIQUE ([TenantId], [AssetTag])
GO


ALTER TABLE [dbo].[ExtinguisherTypes]
ADD CONSTRAINT [UQ__Extingui__3E1CDC7CCA5B96D8] UNIQUE ([TypeCode])
GO


ALTER TABLE [dbo].[Locations]
ADD CONSTRAINT [UQ_Locations_TenantCode] UNIQUE ([TenantId], [LocationCode])
GO


ALTER TABLE [dbo].[SystemRoles]
ADD CONSTRAINT [UQ_SystemRoles_RoleName] UNIQUE ([RoleName])
GO


ALTER TABLE [dbo].[Tenants]
ADD CONSTRAINT [UQ_Tenants_TenantCode] UNIQUE ([TenantCode])
GO


ALTER TABLE [dbo].[UserSystemRoles]
ADD CONSTRAINT [UQ_UserSystemRoles_User_Role] UNIQUE ([UserId], [SystemRoleId])
GO

-- FOREIGN KEYS


ALTER TABLE [dbo].[ChecklistItems]
ADD CONSTRAINT [FK_ChecklistItems_Template] FOREIGN KEY ([TemplateId])
REFERENCES [dbo].[ChecklistTemplates] ([TemplateId]) ON DELETE CASCADE
GO


ALTER TABLE [dbo].[ChecklistItems]
ADD CONSTRAINT [FK_ChecklistItems_Tenants] FOREIGN KEY ([TenantId])
REFERENCES [dbo].[Tenants] ([TenantId])
GO


ALTER TABLE [dbo].[Extinguishers]
ADD CONSTRAINT [FK_Extinguishers_Locations] FOREIGN KEY ([LocationId])
REFERENCES [dbo].[Locations] ([LocationId])
GO


ALTER TABLE [dbo].[Extinguishers]
ADD CONSTRAINT [FK_Extinguishers_Tenants] FOREIGN KEY ([TenantId])
REFERENCES [dbo].[Tenants] ([TenantId])
GO


ALTER TABLE [dbo].[Extinguishers]
ADD CONSTRAINT [FK_Extinguishers_Types] FOREIGN KEY ([ExtinguisherTypeId])
REFERENCES [dbo].[ExtinguisherTypes] ([ExtinguisherTypeId])
GO


ALTER TABLE [dbo].[Extinguishers]
ADD CONSTRAINT [FK_tenant_5827F83D_743D_422D_94D5_90665BDA3506_Ext_Loc] FOREIGN KEY ([LocationId])
REFERENCES [dbo].[Locations] ([LocationId])
GO


ALTER TABLE [dbo].[Extinguishers]
ADD CONSTRAINT [FK_tenant_5827F83D_743D_422D_94D5_90665BDA3506_Ext_Type] FOREIGN KEY ([ExtinguisherTypeId])
REFERENCES [dbo].[ExtinguisherTypes] ([ExtinguisherTypeId])
GO


ALTER TABLE [dbo].[Extinguishers]
ADD CONSTRAINT [FK_tenant_60C74CCA6CD0490193D472F3EFFF38B5_Ext_Location] FOREIGN KEY ([LocationId])
REFERENCES [dbo].[Locations] ([LocationId])
GO


ALTER TABLE [dbo].[Extinguishers]
ADD CONSTRAINT [FK_tenant_60C74CCA6CD0490193D472F3EFFF38B5_Ext_Type] FOREIGN KEY ([ExtinguisherTypeId])
REFERENCES [dbo].[ExtinguisherTypes] ([ExtinguisherTypeId])
GO


ALTER TABLE [dbo].[Extinguishers]
ADD CONSTRAINT [FK_tenant_634F2B52_D32A_46DD_A045_D158E793ADCB_Ext_Loc] FOREIGN KEY ([LocationId])
REFERENCES [dbo].[Locations] ([LocationId])
GO


ALTER TABLE [dbo].[Extinguishers]
ADD CONSTRAINT [FK_tenant_634F2B52_D32A_46DD_A045_D158E793ADCB_Ext_Type] FOREIGN KEY ([ExtinguisherTypeId])
REFERENCES [dbo].[ExtinguisherTypes] ([ExtinguisherTypeId])
GO


ALTER TABLE [dbo].[ExtinguisherTypes]
ADD CONSTRAINT [FK_ExtinguisherTypes_Tenants] FOREIGN KEY ([TenantId])
REFERENCES [dbo].[Tenants] ([TenantId])
GO


ALTER TABLE [dbo].[InspectionChecklistResponses]
ADD CONSTRAINT [FK_InspectionChecklistResponses_ChecklistItem] FOREIGN KEY ([ChecklistItemId])
REFERENCES [dbo].[ChecklistItems] ([ChecklistItemId])
GO


ALTER TABLE [dbo].[InspectionChecklistResponses]
ADD CONSTRAINT [FK_InspectionChecklistResponses_Inspection] FOREIGN KEY ([InspectionId])
REFERENCES [dbo].[Inspections] ([InspectionId]) ON DELETE CASCADE
GO


ALTER TABLE [dbo].[InspectionChecklistResponses]
ADD CONSTRAINT [FK_InspectionChecklistResponses_Tenants] FOREIGN KEY ([TenantId])
REFERENCES [dbo].[Tenants] ([TenantId])
GO


ALTER TABLE [dbo].[InspectionChecklistTemplates]
ADD CONSTRAINT [FK_tenant_60C74CCA6CD0490193D472F3EFFF38B5_CheckTemp_InspType] FOREIGN KEY ([InspectionTypeId])
REFERENCES [dbo].[InspectionTypes] ([InspectionTypeId])
GO


ALTER TABLE [dbo].[InspectionDeficiencies]
ADD CONSTRAINT [FK_InspectionDeficiencies_Inspection] FOREIGN KEY ([InspectionId])
REFERENCES [dbo].[Inspections] ([InspectionId]) ON DELETE CASCADE
GO


ALTER TABLE [dbo].[InspectionDeficiencies]
ADD CONSTRAINT [FK_InspectionDeficiencies_Tenants] FOREIGN KEY ([TenantId])
REFERENCES [dbo].[Tenants] ([TenantId])
GO


ALTER TABLE [dbo].[InspectionPhotos]
ADD CONSTRAINT [FK_InspectionPhotos_Inspection] FOREIGN KEY ([InspectionId])
REFERENCES [dbo].[Inspections] ([InspectionId]) ON DELETE CASCADE
GO


ALTER TABLE [dbo].[InspectionPhotos]
ADD CONSTRAINT [FK_InspectionPhotos_Tenants] FOREIGN KEY ([TenantId])
REFERENCES [dbo].[Tenants] ([TenantId])
GO


ALTER TABLE [dbo].[Inspections]
ADD CONSTRAINT [FK_Inspections_Extinguisher] FOREIGN KEY ([ExtinguisherId])
REFERENCES [dbo].[Extinguishers] ([ExtinguisherId])
GO


ALTER TABLE [dbo].[Inspections]
ADD CONSTRAINT [FK_Inspections_Extinguishers] FOREIGN KEY ([ExtinguisherId])
REFERENCES [dbo].[Extinguishers] ([ExtinguisherId])
GO


ALTER TABLE [dbo].[Inspections]
ADD CONSTRAINT [FK_Inspections_Inspectors] FOREIGN KEY ([InspectorUserId])
REFERENCES [dbo].[Users] ([UserId])
GO


ALTER TABLE [dbo].[Inspections]
ADD CONSTRAINT [FK_Inspections_Tenants] FOREIGN KEY ([TenantId])
REFERENCES [dbo].[Tenants] ([TenantId])
GO


ALTER TABLE [dbo].[Inspections]
ADD CONSTRAINT [FK_Inspections_Types] FOREIGN KEY ([InspectionTypeId])
REFERENCES [dbo].[InspectionTypes] ([InspectionTypeId])
GO


ALTER TABLE [dbo].[Inspections]
ADD CONSTRAINT [FK_tenant_60C74CCA6CD0490193D472F3EFFF38B5_Insp_Extinguisher] FOREIGN KEY ([ExtinguisherId])
REFERENCES [dbo].[Extinguishers] ([ExtinguisherId])
GO


ALTER TABLE [dbo].[Inspections]
ADD CONSTRAINT [FK_tenant_60C74CCA6CD0490193D472F3EFFF38B5_Insp_Type] FOREIGN KEY ([InspectionTypeId])
REFERENCES [dbo].[InspectionTypes] ([InspectionTypeId])
GO


ALTER TABLE [dbo].[InspectionTypes]
ADD CONSTRAINT [FK_InspectionTypes_Tenants] FOREIGN KEY ([TenantId])
REFERENCES [dbo].[Tenants] ([TenantId])
GO


ALTER TABLE [dbo].[Locations]
ADD CONSTRAINT [FK_Locations_Tenants] FOREIGN KEY ([TenantId])
REFERENCES [dbo].[Tenants] ([TenantId])
GO


ALTER TABLE [dbo].[MaintenanceRecords]
ADD CONSTRAINT [FK_MaintenanceRecords_Tenants] FOREIGN KEY ([TenantId])
REFERENCES [dbo].[Tenants] ([TenantId])
GO


ALTER TABLE [dbo].[MaintenanceRecords]
ADD CONSTRAINT [FK_tenant_60C74CCA6CD0490193D472F3EFFF38B5_Maint_Extinguisher] FOREIGN KEY ([ExtinguisherId])
REFERENCES [dbo].[Extinguishers] ([ExtinguisherId])
GO


ALTER TABLE [dbo].[UserSystemRoles]
ADD CONSTRAINT [FK_UserSystemRoles_SystemRoles] FOREIGN KEY ([SystemRoleId])
REFERENCES [dbo].[SystemRoles] ([SystemRoleId])
GO


ALTER TABLE [dbo].[UserSystemRoles]
ADD CONSTRAINT [FK_UserSystemRoles_Users] FOREIGN KEY ([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO


ALTER TABLE [dbo].[UserTenantRoles]
ADD CONSTRAINT [FK_UserTenantRoles_Tenants] FOREIGN KEY ([TenantId])
REFERENCES [dbo].[Tenants] ([TenantId])
GO


ALTER TABLE [dbo].[UserTenantRoles]
ADD CONSTRAINT [FK_UserTenantRoles_Users] FOREIGN KEY ([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO

-- CHECK CONSTRAINTS


ALTER TABLE [dbo].[Tenants]
ADD CONSTRAINT [CK_Tenants_SubscriptionTier] CHECK ([SubscriptionTier]='Premium' OR [SubscriptionTier]='Standard' OR [SubscriptionTier]='Free')
GO


ALTER TABLE [dbo].[UserTenantRoles]
ADD CONSTRAINT [CK_UserTenantRoles_RoleName] CHECK ([RoleName]='Viewer' OR [RoleName]='Inspector' OR [RoleName]='LocationManager' OR [RoleName]='TenantAdmin')
GO

