
/*
 * Database Schema Export
 * Generated by: SQL Extract v1.0.0
 * Date: 2025-10-18 16:41:01
 */

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- INDEXES


CREATE NONCLUSTERED INDEX [IX_AuditLog_EntityType_EntityId]
ON [dbo].[AuditLog] ([EntityType], [EntityId])
INCLUDE ([Action], [Timestamp])
GO


CREATE NONCLUSTERED INDEX [IX_AuditLog_TenantId_Timestamp]
ON [dbo].[AuditLog] ([TenantId], [Timestamp])
GO


CREATE NONCLUSTERED INDEX [IX_AuditLog_UserId_Timestamp]
ON [dbo].[AuditLog] ([UserId], [Timestamp])
WHERE ([UserId] IS NOT NULL)
GO


CREATE NONCLUSTERED INDEX [IX_ChecklistItems_TenantId]
ON [dbo].[ChecklistItems] ([TenantId])
INCLUDE ([ChecklistItemId])
GO


CREATE NONCLUSTERED INDEX [IX_Extinguishers_AssetTag]
ON [dbo].[Extinguishers] ([TenantId], [AssetTag])
GO


CREATE NONCLUSTERED INDEX [IX_Extinguishers_IsActive]
ON [dbo].[Extinguishers] ([TenantId], [IsActive])
GO


CREATE NONCLUSTERED INDEX [IX_Extinguishers_LocationId]
ON [dbo].[Extinguishers] ([LocationId])
GO


CREATE NONCLUSTERED INDEX [IX_Extinguishers_TenantId]
ON [dbo].[Extinguishers] ([TenantId])
GO


CREATE NONCLUSTERED INDEX [IX_Extinguishers_TypeId]
ON [dbo].[Extinguishers] ([ExtinguisherTypeId])
GO


CREATE NONCLUSTERED INDEX [IX_ExtinguisherTypes_IsActive]
ON [dbo].[ExtinguisherTypes] ([IsActive])
GO


CREATE NONCLUSTERED INDEX [IX_ExtinguisherTypes_TenantId]
ON [dbo].[ExtinguisherTypes] ([TenantId])
INCLUDE ([ExtinguisherTypeId])
GO


CREATE NONCLUSTERED INDEX [IX_ExtinguisherTypes_TypeCode]
ON [dbo].[ExtinguisherTypes] ([TypeCode])
GO


CREATE NONCLUSTERED INDEX [IX_InspectionChecklistResponses_TenantId]
ON [dbo].[InspectionChecklistResponses] ([TenantId])
INCLUDE ([ResponseId])
GO


CREATE NONCLUSTERED INDEX [IX_InspectionDeficiencies_TenantId]
ON [dbo].[InspectionDeficiencies] ([TenantId])
INCLUDE ([DeficiencyId])
GO


CREATE NONCLUSTERED INDEX [IX_InspectionPhotos_TenantId]
ON [dbo].[InspectionPhotos] ([TenantId])
INCLUDE ([PhotoId])
GO


CREATE NONCLUSTERED INDEX [IX_Inspections_Date]
ON [dbo].[Inspections] ([TenantId], [InspectionDate])
GO


CREATE NONCLUSTERED INDEX [IX_Inspections_ExtinguisherId]
ON [dbo].[Inspections] ([ExtinguisherId])
GO


CREATE NONCLUSTERED INDEX [IX_Inspections_Hash]
ON [dbo].[Inspections] ([TamperProofHash])
GO


CREATE NONCLUSTERED INDEX [IX_Inspections_Inspector]
ON [dbo].[Inspections] ([InspectorUserId])
GO


CREATE NONCLUSTERED INDEX [IX_Inspections_TenantId]
ON [dbo].[Inspections] ([TenantId])
GO


CREATE NONCLUSTERED INDEX [IX_InspectionTypes_IsActive]
ON [dbo].[InspectionTypes] ([TenantId], [IsActive])
GO


CREATE NONCLUSTERED INDEX [IX_InspectionTypes_TenantId]
ON [dbo].[InspectionTypes] ([TenantId])
GO


CREATE NONCLUSTERED INDEX [IX_Locations_IsActive]
ON [dbo].[Locations] ([TenantId], [IsActive])
GO


CREATE NONCLUSTERED INDEX [IX_Locations_TenantId]
ON [dbo].[Locations] ([TenantId])
GO


CREATE NONCLUSTERED INDEX [IX_Tenants_IsActive]
ON [dbo].[Tenants] ([IsActive])
INCLUDE ([TenantCode], [CompanyName])
GO


CREATE NONCLUSTERED INDEX [IX_Tenants_TenantCode]
ON [dbo].[Tenants] ([TenantCode])
INCLUDE ([IsActive])
GO


CREATE NONCLUSTERED INDEX [IX_Users_AzureAdB2CObjectId]
ON [dbo].[Users] ([AzureAdB2CObjectId])
WHERE ([AzureAdB2CObjectId] IS NOT NULL)
GO


CREATE UNIQUE NONCLUSTERED INDEX [IX_Users_Email]
ON [dbo].[Users] ([Email])
WHERE ([IsActive]=(1))
GO


CREATE NONCLUSTERED INDEX [IX_Users_IsActive]
ON [dbo].[Users] ([IsActive])
GO


CREATE NONCLUSTERED INDEX [IX_UserTenantRoles_TenantId]
ON [dbo].[UserTenantRoles] ([TenantId])
WHERE ([IsActive]=(1))
GO


CREATE NONCLUSTERED INDEX [IX_UserTenantRoles_UserId_TenantId]
ON [dbo].[UserTenantRoles] ([UserId], [TenantId])
INCLUDE ([RoleName], [IsActive])
GO


CREATE UNIQUE NONCLUSTERED INDEX [UQ_UserTenantRoles_User_Tenant_Role]
ON [dbo].[UserTenantRoles] ([UserId], [TenantId], [RoleName])
WHERE ([IsActive]=(1))
GO

