-- Check table schemas
USE FireProofDB;
GO

PRINT 'Checking Extinguishers table schema...';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Extinguishers'
ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'Checking Locations table schema...';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Locations'
ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'Checking Inspections table schema...';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Inspections'
ORDER BY ORDINAL_POSITION;

GO
