name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version/Tag to deploy'
        required: true
        default: 'main'
      reason:
        description: 'Reason for production deployment'
        required: true
      skip_tests:
        description: 'Skip health checks after deployment'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

jobs:
  validate-inputs:
    name: Validate Deployment Request
    runs-on: ubuntu-latest

    steps:
      - name: Log deployment details
        run: |
          echo "🚀 Production Deployment Requested"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Reason: ${{ github.event.inputs.reason }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Skip tests: ${{ github.event.inputs.skip_tests }}"

  deploy-backend-production:
    name: Deploy Backend to Production
    runs-on: ubuntu-latest
    needs: validate-inputs
    environment:
      name: production
      url: https://api.fireproofapp.net

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore backend/FireExtinguisherInspection.API/FireExtinguisherInspection.API.csproj

      - name: Build
        run: dotnet build backend/FireExtinguisherInspection.API/FireExtinguisherInspection.API.csproj --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test backend/FireExtinguisherInspection.API.sln --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish backend/FireExtinguisherInspection.API/FireExtinguisherInspection.API.csproj --configuration Release --no-build --output ./publish-production

      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fireproof-api-test-2025'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PRODUCTION }}
          package: ./publish-production

      - name: Test Production API Health
        if: github.event.inputs.skip_tests == 'false'
        run: |
          echo "Waiting for production backend to start..."
          sleep 45
          echo "Testing health endpoint..."
          curl -f https://fireproof-api-test-2025.azurewebsites.net/health || exit 1
          curl -f https://api.fireproofapp.net/health || echo "Custom domain not responding yet"

  deploy-frontend-production:
    name: Deploy Frontend to Production
    runs-on: ubuntu-latest
    needs: deploy-backend-production
    environment:
      name: production
      url: https://fireproofapp.net

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/fire-extinguisher-web/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend/fire-extinguisher-web
          npm ci

      - name: Build with production config
        run: |
          cd frontend/fire-extinguisher-web
          cp .env .env.local
          npm run build
        env:
          VITE_API_BASE_URL: https://api.fireproofapp.net/api

      - name: Deploy to Azure Static Web App (Production)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_SMOKE_08DBC500F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/frontend/fire-extinguisher-web'
          output_location: 'dist'
          skip_app_build: true

      - name: Test Production Frontend
        if: github.event.inputs.skip_tests == 'false'
        run: |
          sleep 20
          curl -f https://nice-smoke-08dbc500f.2.azurestaticapps.net/ || exit 1
          curl -f https://fireproofapp.net/ || echo "Custom domain not responding yet"

  notify-deployment:
    name: Notify Production Deployment
    runs-on: ubuntu-latest
    needs: [deploy-backend-production, deploy-frontend-production]
    if: always()

    steps:
      - name: Deployment Success
        if: needs.deploy-backend-production.result == 'success' && needs.deploy-frontend-production.result == 'success'
        run: |
          echo "✅ Production deployment successful!"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Backend: https://api.fireproofapp.net"
          echo "Frontend: https://fireproofapp.net"
          echo "Deployed by: ${{ github.actor }}"
          echo "Reason: ${{ github.event.inputs.reason }}"

      - name: Deployment Failed
        if: needs.deploy-backend-production.result != 'success' || needs.deploy-frontend-production.result != 'success'
        run: |
          echo "❌ Production deployment failed!"
          echo "Backend status: ${{ needs.deploy-backend-production.result }}"
          echo "Frontend status: ${{ needs.deploy-frontend-production.result }}"
          exit 1
