name: Deploy to Staging and Production

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for deploying to both environments'
        required: true
      skip_staging:
        description: 'Skip staging deployment'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

jobs:
  deploy-staging:
    name: Deploy to Staging First
    if: github.event.inputs.skip_staging == 'false'
    uses: ./.github/workflows/deploy-staging.yml
    secrets: inherit

  approve-production:
    name: Approve Production Deployment
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.event.inputs.skip_staging == 'false' || github.event.inputs.skip_staging == null
    environment:
      name: production-approval
    steps:
      - name: Await approval
        run: |
          echo "⏳ Staging deployment complete"
          echo "Staging Backend: https://staging-api.fireproofapp.net"
          echo "Staging Frontend: https://staging.fireproofapp.net"
          echo ""
          echo "🚨 Manual approval required before production deployment"
          echo "Reason: ${{ github.event.inputs.reason }}"

  deploy-production:
    name: Deploy to Production
    needs: [deploy-staging, approve-production]
    if: always() && (needs.deploy-staging.result == 'success' || github.event.inputs.skip_staging == 'true')
    uses: ./.github/workflows/deploy-production.yml
    with:
      version: ${{ github.ref_name }}
      reason: ${{ github.event.inputs.reason }}
      skip_tests: 'false'
    secrets: inherit

  notify-completion:
    name: Notify Deployment Completion
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: always()

    steps:
      - name: All Deployments Success
        if: needs.deploy-production.result == 'success'
        run: |
          echo "✅ All environments deployed successfully!"
          echo ""
          echo "Staging:"
          echo "  Backend: https://staging-api.fireproofapp.net"
          echo "  Frontend: https://staging.fireproofapp.net"
          echo ""
          echo "Production:"
          echo "  Backend: https://api.fireproofapp.net"
          echo "  Frontend: https://fireproofapp.net"

      - name: Deployment Failed
        if: needs.deploy-production.result != 'success'
        run: |
          echo "❌ Deployment pipeline failed!"
          echo "Production deployment status: ${{ needs.deploy-production.result }}"
          exit 1
