name: Deploy to Staging

on:
  push:
    branches:
      - staging
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/deploy-staging.yml'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual deployment'
        required: false
        default: 'Manual staging deployment'

jobs:
  deploy-backend-staging:
    name: Deploy Backend to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore backend/FireExtinguisherInspection.API/FireExtinguisherInspection.API.csproj

      - name: Build
        run: dotnet build backend/FireExtinguisherInspection.API/FireExtinguisherInspection.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish backend/FireExtinguisherInspection.API/FireExtinguisherInspection.API.csproj --configuration Release --no-build --output ./publish-staging

      - name: Deploy to Azure Web App (Staging)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fireproof-api-staging'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          package: ./publish-staging

      - name: Test Staging API Health
        run: |
          sleep 30
          curl -f https://fireproof-api-staging.azurewebsites.net/health || exit 1

  deploy-frontend-staging:
    name: Deploy Frontend to Staging
    runs-on: ubuntu-latest
    needs: deploy-backend-staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/fire-extinguisher-web/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend/fire-extinguisher-web
          npm ci

      - name: Build with staging config
        run: |
          cd frontend/fire-extinguisher-web
          cp .env.staging .env.local
          npm run build

      - name: Deploy to Azure Static Web App (Staging)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_STAGING }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/frontend/fire-extinguisher-web'
          output_location: 'dist'
          skip_app_build: true

      - name: Test Staging Frontend
        run: |
          sleep 15
          curl -f https://staging.fireproofapp.net/ || curl -f https://witty-island-0daa2e910.2.azurestaticapps.net/

  notify-deployment:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [deploy-backend-staging, deploy-frontend-staging]
    if: always()

    steps:
      - name: Deployment Success
        if: needs.deploy-backend-staging.result == 'success' && needs.deploy-frontend-staging.result == 'success'
        run: |
          echo "✅ Staging deployment successful!"
          echo "Backend: https://staging-api.fireproofapp.net"
          echo "Frontend: https://staging.fireproofapp.net"

      - name: Deployment Failed
        if: needs.deploy-backend-staging.result != 'success' || needs.deploy-frontend-staging.result != 'success'
        run: |
          echo "❌ Staging deployment failed!"
          echo "Backend status: ${{ needs.deploy-backend-staging.result }}"
          echo "Frontend status: ${{ needs.deploy-frontend-staging.result }}"
          exit 1
