name: Deploy Backend to Production

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend-production.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: fireproof-api-prod
  AZURE_WEBAPP_PACKAGE_PATH: './backend/FireExtinguisherInspection.API'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      run: dotnet restore

    - name: Build application
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      working-directory: ./backend
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish application
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PRODUCTION }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish

    - name: Health check
      run: |
        echo "Waiting 30 seconds for deployment to stabilize..."
        sleep 30
        response=$(curl -s -o /dev/null -w "%{http_code}" https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/health || echo "000")
        if [ "$response" = "200" ]; then
          echo "Health check passed (HTTP $response)"
        else
          echo "Health check failed (HTTP $response)"
          exit 1
        fi

    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Backend production deployment successful!"
        echo "URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"

    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Backend production deployment failed!"
